-- MySQL Script generated by MySQL Workbench
-- 11/08/18 10:51:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema classroom_records
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema classroom_records
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classroom_records` DEFAULT CHARACTER SET latin1 ;
USE `classroom_records` ;

-- -----------------------------------------------------
-- Table `classroom_records`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classroom_records`.`attendance` (
  `AttendanceID` INT(11) NOT NULL,
  `StudentID` INT(11) NULL DEFAULT NULL,
  `TeacherID` INT(11) NULL DEFAULT NULL,
  `ClassID` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`AttendanceID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classroom_records`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classroom_records`.`students` (
  `StudentID` INT(11) NOT NULL,
  `StudentName` VARCHAR(18) NOT NULL,
  `StudentEmail` VARCHAR(40) NOT NULL,
  `ParentName` VARCHAR(18) NOT NULL,
  `ParentPhone` INT(11) NOT NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `classroom_records`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classroom_records`.`teachers` (
  `TeacherID` INT(11) NOT NULL,
  `TeacherName` VARCHAR(45) NULL DEFAULT NULL,
  `TeacherEmail` VARCHAR(45) NULL DEFAULT NULL,
  `TeacherPhone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`TeacherID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
