/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.view.ui.student;

import edu.curd.dto.StudentDTO;
import edu.data.service.ManageStudentService;
import edu.data.service.impl.ManageStudentServiceImpl;
import edu.view.ui.MainForm;
import edu.view.ui.teacher.*;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Kyle
 */
public class StudentDetails extends javax.swing.JDialog {

    public ManageStudentService manageStudentService = new ManageStudentServiceImpl();

    public StudentDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initGUI();
    }

    public StudentDetails(java.awt.Frame parent) {
        super(parent);
        initComponents();
        initGUI();
    }

    private void initGUI() {
        ButtonGroup group = new ButtonGroup();
        group.add(maleOpt);
        group.add(femaleOpt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserLogin2 = new javax.swing.JTextField();
        uName_label2 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        uName_label = new javax.swing.JLabel();
        txtstudentId = new javax.swing.JTextField();
        uName_label1 = new javax.swing.JLabel();
        uName_label3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        maleOpt = new javax.swing.JRadioButton();
        femaleOpt = new javax.swing.JRadioButton();
        uName_label4 = new javax.swing.JLabel();
        txtstudentDOB = new com.toedter.calendar.JDateChooser();
        uName_label5 = new javax.swing.JLabel();
        txtstudentPhoe = new javax.swing.JTextField();
        uName_label6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtstudentAddress = new javax.swing.JTextArea();
        saveStudentButton = new javax.swing.JButton();
        saveStudentButton1 = new javax.swing.JButton();
        txtstudentLName = new javax.swing.JTextField();
        uName_label8 = new javax.swing.JLabel();
        txtstudentFName = new javax.swing.JTextField();

        txtUserLogin2.setBackground(new java.awt.Color(51, 51, 51));
        txtUserLogin2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUserLogin2.setForeground(new java.awt.Color(255, 255, 255));
        txtUserLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserLogin2ActionPerformed(evt);
            }
        });
        txtUserLogin2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserLogin2KeyPressed(evt);
            }
        });

        uName_label2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label2.setForeground(new java.awt.Color(204, 204, 204));
        uName_label2.setText("Last Name");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        header.setBackground(new java.awt.Color(30, 130, 76));
        header.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Student Details");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        content.setBackground(new java.awt.Color(51, 51, 51));

        uName_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label.setForeground(new java.awt.Color(204, 204, 204));
        uName_label.setText("Student ID");

        txtstudentId.setEditable(false);
        txtstudentId.setBackground(new java.awt.Color(51, 51, 51));
        txtstudentId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtstudentId.setForeground(new java.awt.Color(255, 255, 255));
        txtstudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentIdActionPerformed(evt);
            }
        });
        txtstudentId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtstudentIdKeyPressed(evt);
            }
        });

        uName_label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label1.setForeground(new java.awt.Color(204, 204, 204));
        uName_label1.setText("Gender");

        uName_label3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label3.setForeground(new java.awt.Color(204, 204, 204));
        uName_label3.setText("Last Name");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        maleOpt.setBackground(new java.awt.Color(51, 51, 51));
        maleOpt.setForeground(new java.awt.Color(255, 255, 255));
        maleOpt.setSelected(true);
        maleOpt.setText("Male");

        femaleOpt.setBackground(new java.awt.Color(51, 51, 51));
        femaleOpt.setForeground(new java.awt.Color(255, 255, 255));
        femaleOpt.setText("Female");
        femaleOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleOptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(maleOpt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(femaleOpt)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleOpt)
                    .addComponent(femaleOpt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        uName_label4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label4.setForeground(new java.awt.Color(204, 204, 204));
        uName_label4.setText("DOB");

        txtstudentDOB.setBackground(new java.awt.Color(51, 51, 51));
        txtstudentDOB.setForeground(new java.awt.Color(255, 255, 255));
        txtstudentDOB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        uName_label5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label5.setForeground(new java.awt.Color(204, 204, 204));
        uName_label5.setText("Phone");

        txtstudentPhoe.setBackground(new java.awt.Color(51, 51, 51));
        txtstudentPhoe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtstudentPhoe.setForeground(new java.awt.Color(255, 255, 255));
        txtstudentPhoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentPhoeActionPerformed(evt);
            }
        });
        txtstudentPhoe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtstudentPhoeKeyPressed(evt);
            }
        });

        uName_label6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label6.setForeground(new java.awt.Color(204, 204, 204));
        uName_label6.setText("Address");

        txtstudentAddress.setColumns(20);
        txtstudentAddress.setRows(2);
        jScrollPane1.setViewportView(txtstudentAddress);

        saveStudentButton.setBackground(new java.awt.Color(108, 122, 137));
        saveStudentButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        saveStudentButton.setText("Save");
        saveStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStudentButtonActionPerformed(evt);
            }
        });

        saveStudentButton1.setBackground(new java.awt.Color(108, 122, 137));
        saveStudentButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        saveStudentButton1.setText("Close");
        saveStudentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStudentButton1ActionPerformed(evt);
            }
        });

        txtstudentLName.setBackground(new java.awt.Color(51, 51, 51));
        txtstudentLName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtstudentLName.setForeground(new java.awt.Color(255, 255, 255));
        txtstudentLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentLNameActionPerformed(evt);
            }
        });
        txtstudentLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtstudentLNameKeyPressed(evt);
            }
        });

        uName_label8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label8.setForeground(new java.awt.Color(204, 204, 204));
        uName_label8.setText("First Name");

        txtstudentFName.setBackground(new java.awt.Color(51, 51, 51));
        txtstudentFName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtstudentFName.setForeground(new java.awt.Color(255, 255, 255));
        txtstudentFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentFNameActionPerformed(evt);
            }
        });
        txtstudentFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtstudentFNameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveStudentButton1)
                .addGap(161, 161, 161)
                .addComponent(saveStudentButton)
                .addGap(67, 67, 67))
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uName_label)
                            .addComponent(uName_label3)
                            .addComponent(uName_label8))
                        .addGap(48, 48, 48)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstudentPhoe, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstudentDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstudentLName, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstudentFName, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(uName_label6))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(uName_label5))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(uName_label4))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(uName_label1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uName_label)
                            .addComponent(txtstudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtstudentFName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uName_label8))
                        .addGap(39, 39, 39)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtstudentLName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uName_label3))
                        .addGap(50, 50, 50)
                        .addComponent(uName_label1)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uName_label4)
                    .addComponent(txtstudentDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstudentPhoe, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uName_label5))
                .addGap(35, 35, 35)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uName_label6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveStudentButton1)
                    .addComponent(saveStudentButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLogin2ActionPerformed

    private void txtUserLogin2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserLogin2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLogin2KeyPressed

    private void txtstudentFNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstudentFNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentFNameKeyPressed

    private void txtstudentFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentFNameActionPerformed

    private void txtstudentLNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstudentLNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentLNameKeyPressed

    private void txtstudentLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentLNameActionPerformed

    private void saveStudentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStudentButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_saveStudentButton1ActionPerformed

    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

    private void saveStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStudentButtonActionPerformed

        StudentDTO studnetDTO = new StudentDTO();

        if (txtstudentFName.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter Student First Name!");
            return;
        } else if (txtstudentLName.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter Student Last Name!");
            return;
        } else if (txtstudentDOB.isValid()) {
            JOptionPane.showMessageDialog(this, "Please enter Student DOB !");
            return;
        } else if (txtstudentAddress.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter Student Addess!");
            return;
        } else if (txtstudentPhoe.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter Student Phone Number!");
            return;
        } else {
            studnetDTO.setFirstName(txtstudentFName.getText());
            studnetDTO.setLastName(txtstudentLName.getText());
            studnetDTO.setDob(sdf.format(txtstudentDOB.getDate()));
            studnetDTO.setAddress(txtstudentAddress.getText());
            studnetDTO.setPhone(txtstudentPhoe.getText());
            String gender = maleOpt.isSelected() ? "Male" : "Female";
            studnetDTO.setGender(gender);

            int newId = 0;

            if (txtstudentId.getText().isEmpty()) {
                newId = manageStudentService.addNewStudent(studnetDTO);
            } else {
                studnetDTO.setStudentId(Integer.valueOf(txtstudentId.getText()));
                if(manageStudentService.updateStudent(studnetDTO))
                    newId = Integer.valueOf(txtstudentId.getText());
            }

            if (newId > 0) {
                txtstudentId.setText(String.valueOf(newId));
                JOptionPane.showMessageDialog(this, "Details are saved!", "Student Details", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error while saving details!", "Student Details", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveStudentButtonActionPerformed

    public void loadStudentDetails(StudentDTO studnetDTO) {
        txtstudentFName.setText(studnetDTO.getFirstName());
        txtstudentLName.setText(studnetDTO.getLastName());
        txtstudentDOB.setDate(new Date());
        //;.setText(studnetDTO.getDob());
        txtstudentAddress.setText(studnetDTO.getAddress());
        txtstudentPhoe.setText(studnetDTO.getPhone());
        boolean isMale = studnetDTO.getGender().startsWith("M");
        maleOpt.setSelected(isMale);
        txtstudentId.setText(String.valueOf(studnetDTO.getStudentId()));

    }
    private void txtstudentPhoeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstudentPhoeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentPhoeKeyPressed

    private void txtstudentPhoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentPhoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentPhoeActionPerformed

    private void femaleOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleOptActionPerformed

    private void txtstudentIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstudentIdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //     Login();
        }
    }//GEN-LAST:event_txtstudentIdKeyPressed

    private void txtstudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JRadioButton femaleOpt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleOpt;
    private javax.swing.JButton saveStudentButton;
    private javax.swing.JButton saveStudentButton1;
    private javax.swing.JTextField txtUserLogin2;
    private javax.swing.JTextArea txtstudentAddress;
    private com.toedter.calendar.JDateChooser txtstudentDOB;
    private javax.swing.JTextField txtstudentFName;
    private javax.swing.JTextField txtstudentId;
    private javax.swing.JTextField txtstudentLName;
    private javax.swing.JTextField txtstudentPhoe;
    private javax.swing.JLabel uName_label;
    private javax.swing.JLabel uName_label1;
    private javax.swing.JLabel uName_label2;
    private javax.swing.JLabel uName_label3;
    private javax.swing.JLabel uName_label4;
    private javax.swing.JLabel uName_label5;
    private javax.swing.JLabel uName_label6;
    private javax.swing.JLabel uName_label8;
    // End of variables declaration//GEN-END:variables
}
