package Main;

import main.service.myConnection;
import main.entities.Users;

/**
 *
 * @author Kyle
 */
public class UserLogin extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
    }
    private void login(){
        String a = jtfLoginUserName.getText();
        String b = String.valueOf(jtfLoginPassword.getPassword());
      
       if(myConnection.getUser(a,b) != null){
          Users loggedUser =  myConnection.getUser(a,b);
           new ClientHome(loggedUser).setVisible(true);
           this.dispose();
       }else if(myConnection.getCaseUser(a, b) != null){
          Caseworker loggedUser = myConnection.getCaseUser(a, b);
          new CaseHome(loggedUser).setVisible(true);
          this.dispose();
       }else{
            System.out.println("Login Failed");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox2 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jbLoginHelp1 = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        uName_label = new javax.swing.JLabel();
        uPass_label = new javax.swing.JLabel();
        jtfLoginUserName = new javax.swing.JTextField();
        jtfLoginPassword = new javax.swing.JPasswordField();
        exitButton = new javax.swing.JButton();
        registerAcc = new javax.swing.JLabel();
        jbLogin1 = new javax.swing.JButton();

        jCheckBox2.setText("jCheckBox2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        header.setBackground(new java.awt.Color(30, 130, 76));

        logo.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("E.I.T.S");
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        jbLoginHelp1.setBackground(new java.awt.Color(30, 130, 76));
        jbLoginHelp1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbLoginHelp1.setText("Help");
        jbLoginHelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginHelp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(492, Short.MAX_VALUE))
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                    .addContainerGap(661, Short.MAX_VALUE)
                    .addComponent(jbLoginHelp1)
                    .addGap(20, 20, 20)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                    .addContainerGap(42, Short.MAX_VALUE)
                    .addComponent(jbLoginHelp1)
                    .addGap(23, 23, 23)))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        content.setBackground(new java.awt.Color(51, 51, 51));

        uName_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label.setForeground(new java.awt.Color(204, 204, 204));
        uName_label.setText("Username:");

        uPass_label.setBackground(new java.awt.Color(0, 0, 0));
        uPass_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uPass_label.setForeground(new java.awt.Color(204, 204, 204));
        uPass_label.setText("Password:");

        jtfLoginUserName.setBackground(new java.awt.Color(51, 51, 51));
        jtfLoginUserName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtfLoginUserName.setForeground(new java.awt.Color(255, 255, 255));
        jtfLoginUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLoginUserNameActionPerformed(evt);
            }
        });
        jtfLoginUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfLoginUserNameKeyPressed(evt);
            }
        });

        jtfLoginPassword.setBackground(new java.awt.Color(51, 51, 51));
        jtfLoginPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtfLoginPassword.setForeground(new java.awt.Color(255, 255, 255));
        jtfLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLoginPasswordActionPerformed(evt);
            }
        });
        jtfLoginPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfLoginPasswordKeyPressed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(108, 122, 137));
        exitButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        registerAcc.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        registerAcc.setForeground(new java.awt.Color(204, 204, 204));
        registerAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerAcc.setText("Don't have an account? Click here to create one!");
        registerAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerAccMouseClicked(evt);
            }
        });

        jbLogin1.setBackground(new java.awt.Color(108, 122, 137));
        jbLogin1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbLogin1.setText("Login");
        jbLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uName_label)
                            .addComponent(uPass_label))
                        .addGap(18, 18, 18)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jtfLoginUserName))
                        .addGap(14, 14, 14))
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(registerAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jbLogin1)
                            .addGap(44, 44, 44)
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uName_label)
                    .addComponent(jtfLoginUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uPass_label)
                    .addComponent(jtfLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(jbLogin1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerAcc)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoMouseClicked

    private void jtfLoginUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLoginUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLoginUserNameActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void registerAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerAccMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new signUp().setVisible(true);
    }//GEN-LAST:event_registerAccMouseClicked

    private void jtfLoginPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfLoginPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
       login();
        }
    }//GEN-LAST:event_jtfLoginPasswordKeyPressed

    private void jtfLoginUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfLoginUserNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        login();
        }
    }//GEN-LAST:event_jtfLoginUserNameKeyPressed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_exitButtonMouseClicked

    private void jtfLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLoginPasswordActionPerformed

    private void jbLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogin1ActionPerformed
         login();
    }//GEN-LAST:event_jbLogin1ActionPerformed

    private void jbLoginHelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginHelp1ActionPerformed
        new main.HelpPages.LoginHelp().setVisible(true);
    }//GEN-LAST:event_jbLoginHelp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel content;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel header;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JButton jbLogin1;
    private javax.swing.JButton jbLoginHelp1;
    private javax.swing.JPasswordField jtfLoginPassword;
    private javax.swing.JTextField jtfLoginUserName;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel registerAcc;
    private javax.swing.JLabel uName_label;
    private javax.swing.JLabel uPass_label;
    // End of variables declaration//GEN-END:variables
}
