/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.view.ui.student;

import edu.view.ui.teacher.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author Aeron
 */
public class StudentDetails extends javax.swing.JDialog {

    /**
     * Creates new form TeacheLogin
     */
    public StudentDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserLogin2 = new javax.swing.JTextField();
        uName_label2 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        uName_label = new javax.swing.JLabel();
        txtUserLogin = new javax.swing.JTextField();
        uName_label1 = new javax.swing.JLabel();
        uName_label3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        uName_label4 = new javax.swing.JLabel();
        uName_label5 = new javax.swing.JLabel();
        txtUserLogin3 = new javax.swing.JTextField();
        uName_label6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        saveStudentButton = new javax.swing.JButton();
        saveStudentButton1 = new javax.swing.JButton();
        txtUserLogin4 = new javax.swing.JTextField();
        uName_label8 = new javax.swing.JLabel();
        txtUserLogin5 = new javax.swing.JTextField();

        txtUserLogin2.setBackground(new java.awt.Color(51, 51, 51));
        txtUserLogin2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUserLogin2.setForeground(new java.awt.Color(255, 255, 255));
        txtUserLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserLogin2ActionPerformed(evt);
            }
        });
        txtUserLogin2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserLogin2KeyPressed(evt);
            }
        });

        uName_label2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label2.setForeground(new java.awt.Color(204, 204, 204));
        uName_label2.setText("Last Name");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        header.setBackground(new java.awt.Color(30, 130, 76));
        header.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Student Details");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        content.setBackground(new java.awt.Color(51, 51, 51));

        uName_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label.setForeground(new java.awt.Color(204, 204, 204));
        uName_label.setText("Student ID");

        txtUserLogin.setBackground(new java.awt.Color(51, 51, 51));
        txtUserLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserLoginActionPerformed(evt);
            }
        });
        txtUserLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserLoginKeyPressed(evt);
            }
        });

        uName_label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label1.setForeground(new java.awt.Color(204, 204, 204));
        uName_label1.setText("Gender");

        uName_label3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label3.setForeground(new java.awt.Color(204, 204, 204));
        uName_label3.setText("Last Name");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jRadioButton1.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Male");

        jRadioButton2.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        uName_label4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label4.setForeground(new java.awt.Color(204, 204, 204));
        uName_label4.setText("DOB");

        uName_label5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label5.setForeground(new java.awt.Color(204, 204, 204));
        uName_label5.setText("Phone");

        txtUserLogin3.setBackground(new java.awt.Color(51, 51, 51));
        txtUserLogin3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUserLogin3.setForeground(new java.awt.Color(255, 255, 255));
        txtUserLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserLogin3ActionPerformed(evt);
            }
        });
        txtUserLogin3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserLogin3KeyPressed(evt);
            }
        });

        uName_label6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label6.setForeground(new java.awt.Color(204, 204, 204));
        uName_label6.setText("Address");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        saveStudentButton.setBackground(new java.awt.Color(108, 122, 137));
        saveStudentButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        saveStudentButton.setText("Save");
        saveStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStudentButtonActionPerformed(evt);
            }
        });

        saveStudentButton1.setBackground(new java.awt.Color(108, 122, 137));
        saveStudentButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        saveStudentButton1.setText("Clear");
        saveStudentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStudentButton1ActionPerformed(evt);
            }
        });

        txtUserLogin4.setBackground(new java.awt.Color(51, 51, 51));
        txtUserLogin4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUserLogin4.setForeground(new java.awt.Color(255, 255, 255));
        txtUserLogin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserLogin4ActionPerformed(evt);
            }
        });
        txtUserLogin4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserLogin4KeyPressed(evt);
            }
        });

        uName_label8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        uName_label8.setForeground(new java.awt.Color(204, 204, 204));
        uName_label8.setText("First Name");

        txtUserLogin5.setBackground(new java.awt.Color(51, 51, 51));
        txtUserLogin5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUserLogin5.setForeground(new java.awt.Color(255, 255, 255));
        txtUserLogin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserLogin5ActionPerformed(evt);
            }
        });
        txtUserLogin5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserLogin5KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(uName_label)
                                .addGap(52, 52, 52)
                                .addComponent(txtUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uName_label3)
                                    .addComponent(uName_label8))
                                .addGap(48, 48, 48)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtUserLogin5, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                        .addComponent(txtUserLogin4)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uName_label1)
                            .addComponent(uName_label4)
                            .addComponent(uName_label5)
                            .addComponent(uName_label6))
                        .addGap(64, 64, 64)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(saveStudentButton1)
                                .addGap(149, 149, 149)
                                .addComponent(saveStudentButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 42, Short.MAX_VALUE))))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(uName_label)
                                    .addComponent(txtUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUserLogin5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uName_label8))
                                .addGap(39, 39, 39)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUserLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uName_label3))
                                .addGap(50, 50, 50)
                                .addComponent(uName_label1)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(uName_label4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtUserLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(saveStudentButton1))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(saveStudentButton))))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(uName_label5)
                        .addGap(39, 39, 39)
                        .addComponent(uName_label6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLoginActionPerformed

    private void txtUserLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserLoginKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //     Login();
        }
    }//GEN-LAST:event_txtUserLoginKeyPressed

    private void txtUserLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLogin2ActionPerformed

    private void txtUserLogin2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserLogin2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLogin2KeyPressed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void txtUserLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserLogin3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLogin3ActionPerformed

    private void txtUserLogin3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserLogin3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLogin3KeyPressed

    private void saveStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStudentButtonActionPerformed
        //        Login();
    }//GEN-LAST:event_saveStudentButtonActionPerformed

    private void saveStudentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStudentButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveStudentButton1ActionPerformed

    private void txtUserLogin4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserLogin4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLogin4ActionPerformed

    private void txtUserLogin4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserLogin4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLogin4KeyPressed

    private void txtUserLogin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserLogin5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLogin5ActionPerformed

    private void txtUserLogin5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserLogin5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLogin5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton saveStudentButton;
    private javax.swing.JButton saveStudentButton1;
    private javax.swing.JTextField txtUserLogin;
    private javax.swing.JTextField txtUserLogin2;
    private javax.swing.JTextField txtUserLogin3;
    private javax.swing.JTextField txtUserLogin4;
    private javax.swing.JTextField txtUserLogin5;
    private javax.swing.JLabel uName_label;
    private javax.swing.JLabel uName_label1;
    private javax.swing.JLabel uName_label2;
    private javax.swing.JLabel uName_label3;
    private javax.swing.JLabel uName_label4;
    private javax.swing.JLabel uName_label5;
    private javax.swing.JLabel uName_label6;
    private javax.swing.JLabel uName_label8;
    // End of variables declaration//GEN-END:variables
}
